const navigationConfig = {
  '/home': {
    showGoBack: false,
    showHamburgerMenu: true,
    showCart: true,
    showSearch: false,
    showLogo: true,
    showAppName: true,
  },
  '/about': {
    showGoBack: true,
    // ...other settings
  },
  '/payment': {
    showGoBack: true,
    showHamburgerMenu: true,
    showCart: false,
    showSearch: false,
    showLogo: false,
    showAppName: true,
  },
  '/categories': {
    showGoBack: true,
    showHamburgerMenu: true,
    showCart: true,
    showSearch: false,
    showLogo: false,
    showAppName: false,
  },
  '/carrito': {
    showGoBack: true,
    showHamburgerMenu: true,
    showCart: false,
    showSearch: false,
    showLogo: false,
    showAppName: false,
  },
  '/product': {
    showGoBack: true,
    showHamburgerMenu: true,
    showCart: true,
    showSearch: false,
    showLogo: false,
    showAppName: false,
  },
  '/historial': {
    showGoBack: true,
    showHamburgerMenu: false,
    showCart: false,
    showSearch: false,
    showClose: true,
    showLogo: false,
    showAppName: false,
  },
  '/login': {
    showGoBack: false,
    showHamburgerMenu: true,
    showCart: false,
    showSearch: false,
    showClose: false,
    showLogo: true,
    showAppName: false,
    showURI: false,
  },
  '/registrarse': {
    showGoBack: false,
    showHamburgerMenu: true,
    showCart: false,
    showSearch: false,
    showClose: false,
    showLogo: true,
    showAppName: false,
    showURI: false,
  },
  '/recuperar-contrasena': {
    showGoBack: false,
    showHamburgerMenu: true,
    showCart: false,
    showSearch: false,
    showClose: false,
    showLogo: true,
    showAppName: false,
    showURI: false,
  },
  '/recuperar-contrasena/codigo': {
    showGoBack: false,
    showHamburgerMenu: true,
    showCart: false,
    showSearch: false,
    showClose: false,
    showLogo: true,
    showAppName: false,
    showURI: false,
  },
  '/menu': {
    showGoBack: false,
    showHamburgerMenu: false,
    showSearch: false,
    showDarkMode: true,
    showAppName: false,
    showFullName: true,
    showVectorLiquido: true,
  },
  '/profile': {
    showGoBack: true,
    showHamburgerMenu: true,
    showSearch: false,
    showDarkMode: false,
    showAppName: false,
    showFullName: false,
    showVectorLiquido: false,
    customName: 'Editar mi Perfil',
  },
  '/paymentMethods': {
    showGoBack: true,
    showHamburgerMenu: true,
    showSearch: false,
    showDarkMode: false,
    showAppName: false,
    showFullName: false,
    showVectorLiquido: false,
    customName: 'Mis métodos de pago',
  },
  // ...other pages
};

export default navigationConfig;